### ISSUE TITLE
请问有数据库脚本么

### ISSUE THREAD

**Issue by gto999** [calandnong/ling-wu-web-server#8]
问题一：连接ＭＹＳＱＬ只有一个ＬＩＮＧＷＵ数据库名称，表结构及需要哪些表均没有，请问能给出表结构的ＳＱＬ脚本么
问题二：启动项目后一直报 ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...，确认本地ＭＹＳＱＬ服务开启中．如有空，请回答以上，多谢

**Comment by calandnong** [comment]
@gto999 
项目还在开发中，功能还没有完全同步上来，这边麻烦配置一下相关的配置哈，可以先手动在mysql中建一下名为【lingwu】的数据库，然后再尝试进行使用，dev模式下会自动创建表结构。
配置地址：https://github.com/calandnong/ling-wu-web-server/blob/main/packages/pc-server/config/config.development.yaml
